cmake_minimum_required(VERSION 3.25)

# Dependency-free policy check for the four clean-build presets. CMake itself
# validates preset schema/expansion; this verifies project-specific invariants.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../CMakePresets.json" presets)

function(expect expected)
    string(JSON actual GET "${presets}" ${ARGN})
    if(NOT "${actual}" STREQUAL "${expected}")
        message(FATAL_ERROR "Preset field [${ARGN}]: expected '${expected}', got '${actual}'")
    endif()
endfunction()

expect(6 version)
expect(base configurePresets 0 name)
expect(ON configurePresets 0 hidden)
expect(Ninja configurePresets 0 generator)
expect("\${sourceDir}/out/build/\${presetName}" configurePresets 0 binaryDir)
expect(ON configurePresets 0 cacheVariables BUILD_TESTING)

foreach(section configurePresets buildPresets testPresets)
    string(JSON count LENGTH "${presets}" ${section})
    if(section STREQUAL "configurePresets")
        set(expected_count 5)
    else()
        set(expected_count 4)
    endif()
    if(NOT count EQUAL expected_count)
        message(FATAL_ERROR "Unexpected ${section} count: ${count}")
    endif()
endforeach()

set(index 0)
foreach(platform windows linux)
    if(platform STREQUAL "windows")
        set(system Windows)
        set(compiler cl)
    else()
        set(system Linux)
        set(compiler g++)
    endif()
    foreach(config Debug Release)
        string(TOLOWER "${config}" lower_config)
        set(name "${platform}-x64-${lower_config}")
        math(EXPR configure_index "${index} + 1")
        expect("${name}" configurePresets ${configure_index} name)
        expect(base configurePresets ${configure_index} inherits)
        expect(equals configurePresets ${configure_index} condition type)
        expect("\${hostSystemName}" configurePresets ${configure_index} condition lhs)
        expect("${system}" configurePresets ${configure_index} condition rhs)
        expect("${config}" configurePresets ${configure_index} cacheVariables CMAKE_BUILD_TYPE)
        expect("${compiler}" configurePresets ${configure_index} cacheVariables CMAKE_CXX_COMPILER)
        if(platform STREQUAL "windows")
            expect(x64 configurePresets ${configure_index} architecture value)
            expect(external configurePresets ${configure_index} architecture strategy)
        endif()
        foreach(section buildPresets testPresets)
            expect("${name}" ${section} ${index} name)
            expect("${name}" ${section} ${index} configurePreset)
        endforeach()
        expect(error testPresets ${index} execution noTestsAction)
        expect(30 testPresets ${index} execution timeout)
        expect(ON testPresets ${index} output outputOnFailure)
        expect("\${sourceDir}/out/build/\${presetName}/ctest.log" testPresets ${index} output outputLogFile)
        expect("\${sourceDir}/out/build/\${presetName}/junit.xml" testPresets ${index} output outputJUnitFile)
        math(EXPR index "${index} + 1")
    endforeach()
endforeach()
# A standalone -P process does not inherit the root project's policy version.
# CMake 4 can mask missing declarations that still fail on supported CMake 3.
foreach(script IN ITEMS
        ../cmake/CheckCoreIncludes.cmake
        boundary/run_case.cmake
        guest_range_repeatability.cmake)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/${script}" source)
    if(NOT source MATCHES "^cmake_minimum_required\\(VERSION 3\\.25\\)")
        message(FATAL_ERROR "Standalone script lacks the 3.25 policy baseline: ${script}")
    endif()
endforeach()
message(STATUS "Four isolated presets and standalone policy baselines match the clean-build contract")
