cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED GRAPHICS_TEST OR NOT EXISTS "${GRAPHICS_TEST}")
    message(FATAL_ERROR "Graphics replay executable required")
endif()
foreach(attempt RANGE 1 2)
    execute_process(COMMAND "${GRAPHICS_TEST}" RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 12)
    string(REPLACE "\r\n" "\n" output "${output}")
    string(STRIP "${output}" output)
    if(NOT "${status}" STREQUAL "0" OR NOT "${errors}" STREQUAL "" OR
       NOT output MATCHES "^graphics-replay-v1 default-factory=verified fresh=2 repetitions=2 clear=verified rectangle=verified origin=verified shared-edge=verified draw-order=verified invalid=verified close=verified validation-errors=0 checks=[1-9][0-9]*$")
        message(FATAL_ERROR "Replay failed (${status}): ${output}\n${errors}")
    endif()
    if(attempt EQUAL 2 AND NOT "${output}" STREQUAL "${previous}")
        message(FATAL_ERROR "Graphics semantic replay differs between processes")
    endif()
    set(previous "${output}")
endforeach()
message(STATUS "${previous}")
