cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED MEMORY_TEST OR NOT EXISTS "${MEMORY_TEST}")
    message(FATAL_ERROR "Guest-memory integration executable required")
endif()
set(expected "guest-memory-integration-v1: zero write read bounds permissions isolation remap worker clock PASS")
foreach(attempt RANGE 1 2)
    execute_process(COMMAND "${MEMORY_TEST}" RESULT_VARIABLE status
        OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 10)
    string(REPLACE "\r\n" "\n" output "${output}")
    string(STRIP "${output}" output)
    if(NOT "${status}" STREQUAL "0" OR NOT "${output}" STREQUAL "${expected}" OR NOT "${errors}" STREQUAL "")
        message(FATAL_ERROR "Guest-memory semantic summary failed: ${status}: ${output}: ${errors}")
    endif()
endforeach()
message(STATUS "Guest-memory semantic summary matches common host-independent expectation twice")
