if(NOT DEFINED INTERPRETER_TEST)
    message(FATAL_ERROR "INTERPRETER_TEST is required")
endif()
foreach(run RANGE 1 2)
    execute_process(COMMAND "${INTERPRETER_TEST}" --trace
        RESULT_VARIABLE result OUTPUT_VARIABLE trace_${run} ERROR_VARIABLE errors TIMEOUT 20)
    if(NOT result EQUAL 0 OR NOT errors STREQUAL "")
        message(FATAL_ERROR "Replay ${run} failed: ${result}: ${errors}")
    endif()
    string(STRIP "${trace_${run}}" trace_${run})
    string(LENGTH "${trace_${run}}" length)
    if(NOT length EQUAL 13761 OR NOT trace_${run} MATCHES "^PXI1:[0-9a-f]+$")
        message(FATAL_ERROR "Malformed full-state trace")
    endif()
endforeach()
if(NOT trace_1 STREQUAL trace_2)
    message(FATAL_ERROR "Full-state instruction traces differ")
endif()
