cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/validate-trace.cmake")
if(NOT DEFINED FIXTURE OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "FIXTURE and OUTPUT_DIR are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(fixture_arguments)
if(DEFINED ROUTE)
    list(APPEND fixture_arguments "${ROUTE}")
endif()
foreach(run RANGE 1 2)
    set(path "${OUTPUT_DIR}/dispatcher-${run}.json")
    execute_process(COMMAND "${FIXTURE}" ${fixture_arguments} "${path}"
        WORKING_DIRECTORY "${OUTPUT_DIR}" RESULT_VARIABLE result TIMEOUT 10)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "Fixture execution ${run} failed: ${result}")
    endif()
    file(READ "${path}" trace)
    pcsx5_validate_trace("${trace}" error)
    if(error)
        message(FATAL_ERROR "Fixture summary rejected: ${error}")
    endif()
    file(SHA256 "${path}" hash_${run})
endforeach()
if(NOT hash_1 STREQUAL hash_2)
    message(FATAL_ERROR "Repeated fixture semantic summaries differ")
endif()
message(STATUS "Two asserted executions produced identical normalized semantic summaries: ${hash_1}")
