cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/validate-trace.cmake")
file(READ "${CMAKE_CURRENT_LIST_DIR}/synthetic-trace.json" valid)
pcsx5_validate_trace("${valid}" error)
if(error)
    message(FATAL_ERROR "Valid sample rejected: ${error}")
endif()

function(expect_rejected label candidate)
    pcsx5_validate_trace("${candidate}" error)
    if(NOT error)
        message(FATAL_ERROR "Invalid trace accepted: ${label}")
    endif()
endfunction()

expect_rejected("malformed JSON" "{")
expect_rejected("array root" "[]")
string(JSON candidate SET "${valid}" schema_version 2)
expect_rejected("unknown version" "${candidate}")
string(JSON candidate SET "${valid}" schema_version "\"1\"")
expect_rejected("string version" "${candidate}")
string(JSON candidate SET "${valid}" timestamp "\"2026-09-08\"")
expect_rejected("nondeterministic extra metadata" "${candidate}")
string(JSON candidate REMOVE "${valid}" fixture)
expect_rejected("missing fixture" "${candidate}")
string(JSON candidate SET "${valid}" fixture "\"../retail\"")
expect_rejected("invalid fixture identifier" "${candidate}")
string(JSON candidate SET "${valid}" events "[]")
expect_rejected("empty events" "${candidate}")
string(JSON candidate SET "${valid}" events 1 sequence 0)
expect_rejected("duplicate sequence" "${candidate}")
string(JSON candidate SET "${valid}" events 1 sequence 1.5)
expect_rejected("fractional sequence" "${candidate}")
string(JSON candidate SET "${valid}" events 1 kind "\"timestamp\"")
expect_rejected("unknown kind" "${candidate}")
string(JSON candidate SET "${valid}" events 1 subject "\"Host Address\"")
expect_rejected("invalid subject" "${candidate}")
foreach(value "0x2a" "0x000000000000002A" "guest-code+0x1" "host:0x0000000000000000" "42" "pass;fail")
    string(JSON candidate SET "${valid}" events 1 value "\"${value}\"")
    expect_rejected("invalid value ${value}" "${candidate}")
endforeach()
string(JSON candidate SET "${valid}" events 1 value 42)
expect_rejected("numeric value loses u64 fidelity" "${candidate}")
string(JSON candidate SET "${valid}" events 1 thread_id 1234)
expect_rejected("extra event field" "${candidate}")
message(STATUS "Trace contract: valid sample and 20 rejection cases passed")
