cmake_minimum_required(VERSION 3.25)

# Deliberately implements only trace-v1.schema.json, not arbitrary JSON Schema.
function(pcsx5_trace_keys json expected output)
    string(JSON count ERROR_VARIABLE error LENGTH "${json}")
    if(error)
        set(${output} "invalid JSON object: ${error}" PARENT_SCOPE)
        return()
    endif()
    set(actual)
    if(count GREATER 0)
        math(EXPR last "${count} - 1")
        foreach(index RANGE 0 ${last})
            string(JSON key ERROR_VARIABLE error MEMBER "${json}" ${index})
            if(error)
                set(${output} "expected an object" PARENT_SCOPE)
                return()
            endif()
            list(APPEND actual "${key}")
        endforeach()
    endif()
    list(SORT actual)
    list(SORT expected)
    if(NOT "${actual}" STREQUAL "${expected}")
        set(${output} "unexpected object fields: ${actual}" PARENT_SCOPE)
    else()
        set(${output} "" PARENT_SCOPE)
    endif()
endfunction()

function(pcsx5_validate_trace json output)
    pcsx5_trace_keys("${json}" "schema_version;fixture;events" error)
    if(error)
        set(${output} "${error}" PARENT_SCOPE)
        return()
    endif()
    foreach(pair "schema_version;NUMBER" "fixture;STRING" "events;ARRAY")
        list(GET pair 0 key)
        list(GET pair 1 expected)
        string(JSON type TYPE "${json}" "${key}")
        if(NOT type STREQUAL expected)
            set(${output} "wrong type for ${key}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    string(JSON version GET "${json}" schema_version)
    string(JSON fixture GET "${json}" fixture)
    string(JSON count LENGTH "${json}" events)
    if(NOT version STREQUAL "1" OR NOT fixture MATCHES "^[a-z][a-z0-9_]*$" OR count LESS 1)
        set(${output} "invalid version, fixture identifier or empty event list" PARENT_SCOPE)
        return()
    endif()
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
        string(JSON event GET "${json}" events ${index})
        pcsx5_trace_keys("${event}" "sequence;kind;subject;value" error)
        if(error)
            set(${output} "event ${index}: ${error}" PARENT_SCOPE)
            return()
        endif()
        foreach(pair "sequence;NUMBER" "kind;STRING" "subject;STRING" "value;STRING")
            list(GET pair 0 key)
            list(GET pair 1 expected)
            string(JSON type TYPE "${event}" "${key}")
            if(NOT type STREQUAL expected)
                set(${output} "event ${index}: wrong type for ${key}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
        string(JSON sequence GET "${event}" sequence)
        string(JSON kind GET "${event}" kind)
        string(JSON subject GET "${event}" subject)
        string(JSON value GET "${event}" value)
        if(NOT sequence STREQUAL "${index}")
            set(${output} "event ${index}: sequence must match index" PARENT_SCOPE)
            return()
        endif()
        if(NOT kind MATCHES "^(enter|exit|register|fault|tls|check)$" OR
           NOT subject MATCHES "^[a-z][a-z0-9_]*$")
            set(${output} "event ${index}: invalid kind or subject" PARENT_SCOPE)
            return()
        endif()
        if(value MATCHES "^(pass|fail|unknown)$")
            continue()
        endif()
        if(NOT value MATCHES "^(0x|[a-z][a-z0-9-]*\\+0x)([0-9a-f]+)$")
            set(${output} "event ${index}: invalid normalized value" PARENT_SCOPE)
            return()
        endif()
        string(LENGTH "${CMAKE_MATCH_2}" hex_length)
        if(NOT hex_length EQUAL 16)
            set(${output} "event ${index}: value must use 16 hexadecimal digits" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${output} "" PARENT_SCOPE)
endfunction()

if(DEFINED TRACE_FILE)
    file(READ "${TRACE_FILE}" trace)
    pcsx5_validate_trace("${trace}" error)
    if(error)
        message(FATAL_ERROR "Trace rejected: ${error}")
    endif()
    message(STATUS "Trace v1 validated: ${TRACE_FILE}")
endif()
