cmake_minimum_required(VERSION 3.25)
include("${CMAKE_CURRENT_LIST_DIR}/validate-trace.cmake")
get_filename_component(repository_root "${CMAKE_CURRENT_LIST_DIR}/../.." REALPATH)
file(READ "${CMAKE_CURRENT_LIST_DIR}/fixture-provenance.json" manifest)
pcsx5_trace_keys("${manifest}" "schema_version;scope;fixtures" error)
if(error)
    message(FATAL_ERROR "Invalid fixture manifest: ${error}")
endif()
foreach(pair "schema_version;NUMBER" "scope;STRING" "fixtures;ARRAY")
    list(GET pair 0 key)
    list(GET pair 1 expected)
    string(JSON type TYPE "${manifest}" "${key}")
    if(NOT type STREQUAL expected)
        message(FATAL_ERROR "Invalid fixture manifest type: ${key}")
    endif()
endforeach()
string(JSON version GET "${manifest}" schema_version)
string(JSON count LENGTH "${manifest}" fixtures)
if(NOT version STREQUAL "1" OR count LESS 1)
    message(FATAL_ERROR "Invalid fixture manifest version or count")
endif()
math(EXPR last "${count} - 1")
set(seen_ids)
foreach(index RANGE 0 ${last})
    string(JSON record GET "${manifest}" fixtures ${index})
    pcsx5_trace_keys("${record}" "id;path;sha256_lf;origin;authorship;inputs;review" error)
    if(error)
        message(FATAL_ERROR "Invalid fixture ${index}: ${error}")
    endif()
    foreach(key id path sha256_lf origin authorship inputs review)
        string(JSON type TYPE "${record}" "${key}")
        if(NOT type STREQUAL "STRING")
            message(FATAL_ERROR "Fixture ${index}: ${key} must be a string")
        endif()
        string(JSON "${key}" GET "${record}" "${key}")
    endforeach()
    if(NOT id MATCHES "^[a-z][a-z0-9_]*$" OR id IN_LIST seen_ids)
        message(FATAL_ERROR "Invalid or duplicate fixture ID: ${id}")
    endif()
    list(APPEND seen_ids "${id}")
    if(NOT path MATCHES "^tests/[a-zA-Z0-9_./-]+$" OR path MATCHES "(^|/)\\.\\.(/|$)")
        message(FATAL_ERROR "Fixture path must remain within tests/: ${path}")
    endif()
    get_filename_component(resolved "${repository_root}/${path}" REALPATH)
    set(tests_root "${repository_root}/tests")
    cmake_path(IS_PREFIX tests_root "${resolved}" NORMALIZE contained)
    if(NOT contained OR NOT EXISTS "${resolved}" OR IS_DIRECTORY "${resolved}")
        message(FATAL_ERROR "Missing or escaped fixture file: ${path}")
    endif()
    if(NOT origin MATCHES "^(legacy-repository|authored-in-this-rebuild)$" OR
       NOT authorship MATCHES "^(VERIFIED|INFERRED|UNKNOWN)$" OR
       NOT inputs STREQUAL "locally-generated-synthetic" OR review STREQUAL "")
        message(FATAL_ERROR "Invalid provenance classification for ${id}")
    endif()
    file(READ "${resolved}" source)
    string(REPLACE "\r\n" "\n" normalized "${source}")
    string(SHA256 actual "${normalized}")
    if(NOT actual STREQUAL sha256_lf)
        message(FATAL_ERROR "Fixture ${id} changed; review provenance and update hash")
    endif()
endforeach()
message(STATUS "Fixture provenance: ${count} records match reviewed source hashes; classifications are not legal clearance")
