include_guard(GLOBAL)

# Phase 1 is intentionally conservative: no dependency, generated source,
# module, PCH or opaque generator-expression route is approved for the core.
function(pcsx5_boundary_fail reason detail)
    message(FATAL_ERROR "PCSX5_CORE_BOUNDARY[${reason}]: ${detail}")
endfunction()

function(pcsx5_boundary_has_value output value)
    if(NOT "${value}" STREQUAL "" AND NOT "${value}" MATCHES "(^|-)NOTFOUND$")
        set(${output} TRUE PARENT_SCOPE)
    else()
        set(${output} FALSE PARENT_SCOPE)
    endif()
endfunction()

# Preserve quoted tokens while removing comments. Regex-only comment removal
# could erase a real include between two strings containing /* and */.
function(pcsx5_boundary_strip_comments output source)
    if(source MATCHES "(^|[^a-zA-Z0-9_])R\"")
        pcsx5_boundary_fail(preprocessor "Raw string literals need a reviewed scanner extension")
    endif()
    set(result "")
    set(state code)
    set(escaped FALSE)
    string(LENGTH "${source}" length)
    set(index 0)
    while(index LESS length)
        string(SUBSTRING "${source}" ${index} 1 char)
        math(EXPR following "${index} + 1")
        set(next "")
        if(following LESS length)
            string(SUBSTRING "${source}" ${following} 1 next)
        endif()
        if(state STREQUAL "line")
            if(char STREQUAL "\n")
                set(state code)
                string(APPEND result "\n")
            endif()
        elseif(state STREQUAL "block")
            if(char STREQUAL "*" AND next STREQUAL "/")
                set(state code)
                math(EXPR index "${index} + 1")
            elseif(char STREQUAL "\n")
                string(APPEND result "\n")
            endif()
        elseif(state STREQUAL "quote")
            string(APPEND result "${char}")
            if(escaped)
                set(escaped FALSE)
            elseif(char STREQUAL "\\")
                set(escaped TRUE)
            elseif(char STREQUAL delimiter)
                set(state code)
            elseif(char STREQUAL "\n")
                pcsx5_boundary_fail(preprocessor "Unterminated quoted token")
            endif()
        elseif(char STREQUAL "/" AND next STREQUAL "/")
            set(state line)
            string(APPEND result " ")
            math(EXPR index "${index} + 1")
        elseif(char STREQUAL "/" AND next STREQUAL "*")
            set(state block)
            string(APPEND result " ")
            math(EXPR index "${index} + 1")
        else()
            string(APPEND result "${char}")
            set(separator FALSE)
            if(char STREQUAL "'" AND index GREATER 0)
                math(EXPR previous "${index} - 1")
                string(SUBSTRING "${source}" ${previous} 1 before)
                if(before MATCHES "[a-zA-Z0-9]" AND next MATCHES "[a-zA-Z0-9]")
                    set(separator TRUE)
                endif()
            endif()
            if(char STREQUAL "\"" OR (char STREQUAL "'" AND NOT separator))
                set(state quote)
                set(delimiter "${char}")
            endif()
        endif()
        math(EXPR index "${index} + 1")
    endwhile()
    if(state STREQUAL "block" OR state STREQUAL "quote")
        pcsx5_boundary_fail(preprocessor "Unterminated core comment/quoted token")
    endif()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(pcsx5_boundary_owned path root)
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        pcsx5_boundary_fail(source "Missing/non-file core input: ${path}")
    endif()
    file(REAL_PATH "${root}" real_root)
    file(REAL_PATH "${path}" real_path)
    cmake_path(IS_PREFIX real_root "${real_path}" NORMALIZE inside)
    if(NOT inside)
        pcsx5_boundary_fail(source "Input escapes core: ${path}")
    endif()
endfunction()

function(pcsx5_check_core_includes root)
    # Explicitly reviewed standard C++ headers; extend with a regression test
    # when another portable header is needed. No platform C header is implicit.
    set(standard_headers
        algorithm array atomic bit bitset charconv chrono compare concepts
        condition_variable cstddef cstdint cstring deque exception expected
        functional initializer_list iterator limits map memory mutex new numeric
        optional queue ranges ratio set source_location span stack stdexcept
        stop_token string string_view system_error thread tuple type_traits
        unordered_map unordered_set utility variant vector version)
    if(CMAKE_SCRIPT_MODE_FILE)
        file(GLOB_RECURSE inputs "${root}/*")
    else()
        file(GLOB_RECURSE inputs CONFIGURE_DEPENDS "${root}/*")
    endif()
    foreach(path IN LISTS inputs)
        if(path MATCHES "/CMakeLists\\.txt$")
            continue()
        endif()
        pcsx5_boundary_owned("${path}" "${root}")
        if(NOT path MATCHES "\\.(cpp|h|hpp|cc|cxx|hh|hxx|inc|inl)$")
            pcsx5_boundary_fail(source "Unreviewed core file type: ${path}")
        endif()
        file(READ "${path}" source)
        string(ASCII 11 vertical_tab)
        string(ASCII 12 form_feed)
        if(source MATCHES "[${vertical_tab}${form_feed}]")
            pcsx5_boundary_fail(preprocessor "Unsupported control whitespace in ${path}")
        endif()
        # Escaped newlines and alternate directive spellings need a real
        # preprocessor, so reject them instead of claiming to parse them.
        if(source MATCHES "\\\\[\r\n]" OR source MATCHES "%:" OR source MATCHES "\\?\\?=")
            pcsx5_boundary_fail(preprocessor "Unsupported directive spelling in ${path}")
        endif()
        pcsx5_boundary_strip_comments(source "${source}")
        string(REPLACE ";" "\\;" source "${source}")
        string(REPLACE "\n" ";" lines "${source}")
        foreach(line IN LISTS lines)
            string(STRIP "${line}" line)
            if(line MATCHES "^#[ \t]*pragma([ \t]|$)" AND NOT line MATCHES "^#[ \t]*pragma[ \t]+once$")
                pcsx5_boundary_fail(preprocessor "Only pragma once is approved in ${path}")
            endif()
            if(line MATCHES "^(export[ \t]+)?import[ \t<\"]" OR
               line MATCHES "^#[ \t]*(include_next|import)([ \t<\"]|$)")
                pcsx5_boundary_fail(preprocessor "Unsupported import/include_next in ${path}")
            endif()
            if(NOT line MATCHES "^#[ \t]*include([ \t<\"]|$)")
                continue()
            endif()
            if(line MATCHES "^#[ \t]*include[ \t]*<([^<>]+)>[ \t]*$")
                set(header "${CMAKE_MATCH_1}")
                if(header IN_LIST standard_headers)
                    # A source-directory sibling must not shadow an approved
                    # standard header through a quoted include.
                    continue()
                endif()
                if(NOT header MATCHES "^pcsx5/core/[^:]+$")
                    pcsx5_boundary_fail(include "Unapproved header <${header}> in ${path}")
                endif()
                set(included "${root}/include/${header}")
            elseif(line MATCHES "^#[ \t]*include[ \t]*\"([^\"]+)\"[ \t]*$")
                set(header "${CMAKE_MATCH_1}")
                if(IS_ABSOLUTE "${header}" OR header MATCHES "[\\\\:]")
                    pcsx5_boundary_fail(include "Nonportable include ${header} in ${path}")
                endif()
                get_filename_component(parent "${path}" DIRECTORY)
                set(included "${parent}/${header}")
                if(NOT EXISTS "${included}")
                    set(included "${root}/include/${header}")
                endif()
            else()
                pcsx5_boundary_fail(preprocessor "Nonliteral or malformed include in ${path}: ${line}")
            endif()
            pcsx5_boundary_owned("${included}" "${root}")
            if(NOT included MATCHES "\\.(h|hpp|hh|hxx|inc|inl)$")
                pcsx5_boundary_fail(include "Unreviewed core header type: ${included}")
            endif()
        endforeach()
    endforeach()
endfunction()

function(pcsx5_check_core_target target root)
    if(NOT TARGET "${target}")
        pcsx5_boundary_fail(target "Missing target ${target}")
    endif()
    file(REAL_PATH "${root}" root)
    get_target_property(source_dir "${target}" SOURCE_DIR)
    get_target_property(target_type "${target}" TYPE)
    if(NOT target_type STREQUAL "STATIC_LIBRARY")
        pcsx5_boundary_fail(target "Core must be an ordinary static library")
    endif()
    foreach(property IN ITEMS LINK_LIBRARIES INTERFACE_LINK_LIBRARIES
            INTERFACE_LINK_LIBRARIES_DIRECT INTERFACE_LINK_LIBRARIES_DIRECT_EXCLUDE
            LINK_OPTIONS INTERFACE_LINK_OPTIONS LINK_DIRECTORIES INTERFACE_LINK_DIRECTORIES
            PRECOMPILE_HEADERS INTERFACE_PRECOMPILE_HEADERS PRECOMPILE_HEADERS_REUSE_FROM
            INTERFACE_SOURCES COMPILE_DEFINITIONS INTERFACE_COMPILE_DEFINITIONS
            COMPILE_FLAGS LINK_FLAGS RULE_LAUNCH_COMPILE RULE_LAUNCH_LINK)
        get_target_property(value "${target}" "${property}")
        pcsx5_boundary_has_value(present "${value}")
        if(present)
            pcsx5_boundary_fail(property "${target}.${property} is not approved: ${value}")
        endif()
    endforeach()
    foreach(property IN ITEMS INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES
            INTERFACE_SYSTEM_INCLUDE_DIRECTORIES)
        get_target_property(roots "${target}" "${property}")
        pcsx5_boundary_has_value(present "${roots}")
        if(NOT present)
            continue()
        endif()
        foreach(include_root IN LISTS roots)
            if(include_root MATCHES "\\$<" OR NOT IS_DIRECTORY "${include_root}")
                pcsx5_boundary_fail(include_root "Opaque/missing include root: ${include_root}")
            endif()
            file(REAL_PATH "${include_root}" include_root)
            if(NOT include_root STREQUAL "${root}/include")
                pcsx5_boundary_fail(include_root "Only core/include is approved: ${include_root}")
            endif()
        endforeach()
    endforeach()
    foreach(property IN ITEMS COMPILE_OPTIONS INTERFACE_COMPILE_OPTIONS)
        get_target_property(options "${target}" "${property}")
        pcsx5_boundary_has_value(present "${options}")
        if(present)
            foreach(option IN LISTS options)
                if(NOT option MATCHES "^(/W4|/permissive-|/Zc:__cplusplus|-Wall|-Wextra|-Wpedantic|-Wconversion)$")
                    pcsx5_boundary_fail(option "Unreviewed core compiler option: ${option}")
                endif()
            endforeach()
        endif()
    endforeach()
    # Directory definitions can be added after target creation, unlike ordinary
    # target properties; inspect the core directory and every ancestor.
    set(directory "${source_dir}")
    while(directory)
        get_directory_property(definitions DIRECTORY "${directory}" COMPILE_DEFINITIONS)
        pcsx5_boundary_has_value(present "${definitions}")
        if(present)
            pcsx5_boundary_fail(property "Directory COMPILE_DEFINITIONS: ${definitions}")
        endif()
        get_directory_property(directory DIRECTORY "${directory}" PARENT_DIRECTORY)
    endwhile()
    foreach(variable IN ITEMS CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG
            CMAKE_CXX_FLAGS_RELEASE CMAKE_CXX_FLAGS_RELWITHDEBINFO CMAKE_CXX_FLAGS_MINSIZEREL)
        get_directory_property(flags DIRECTORY "${source_dir}" DEFINITION "${variable}")
        if("${flags}" MATCHES "(^|[ \t])(-I|-include|-imacros|-isystem|-idirafter|-fmodule|-fplugin|--sysroot|/I|/FI|/FU|/AI|/external:I|@)")
            pcsx5_boundary_fail(option "Header/module injection through ${variable}")
        endif()
    endforeach()
    get_target_property(sources "${target}" SOURCES)
    pcsx5_boundary_has_value(present "${sources}")
    if(NOT present)
        pcsx5_boundary_fail(source "Core source list is empty")
    endif()
    foreach(source IN LISTS sources)
        if(source MATCHES "\\$<")
            pcsx5_boundary_fail(source "Opaque core source: ${source}")
        endif()
        get_filename_component(path "${source}" ABSOLUTE BASE_DIR "${source_dir}")
        pcsx5_boundary_owned("${path}" "${root}")
        foreach(property IN ITEMS GENERATED EXTERNAL_OBJECT COMPILE_FLAGS COMPILE_OPTIONS
                COMPILE_DEFINITIONS INCLUDE_DIRECTORIES OBJECT_DEPENDS)
            get_source_file_property(value "${path}" TARGET_DIRECTORY "${target}" "${property}")
            pcsx5_boundary_has_value(present "${value}")
            if(property STREQUAL "GENERATED" OR property STREQUAL "EXTERNAL_OBJECT")
                # These two are booleans, unlike lists where OFF is real data.
                set(present "${value}")
            endif()
            if(present)
                pcsx5_boundary_fail(source "Unapproved source ${property}: ${path}")
            endif()
        endforeach()
    endforeach()
    pcsx5_check_core_includes("${root}")
endfunction()
