cmake_minimum_required(VERSION 3.25)

# Build-generated, private shader words. Decode explicitly rather than relying on
# the host byte order or alignment of a reinterpreted byte array.
foreach(argument VERT FRAG OUTPUT)
    if(NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
        message(FATAL_ERROR "Missing shader embedding argument: ${argument}")
    endif()
endforeach()
set(header "// Generated from validated repository-owned shaders; do not edit.\n#pragma once\n#include <array>\n#include <cstdint>\nnamespace pcsx5::graphics::detail {\n")
foreach(stage VERT FRAG)
    file(READ "${${stage}}" bytes HEX)
    string(LENGTH "${bytes}" hex_length)
    math(EXPR remainder "${hex_length} % 8")
    if(hex_length LESS 40 OR NOT remainder EQUAL 0)
        message(FATAL_ERROR "Invalid SPIR-V word length: ${${stage}}")
    endif()
    string(SUBSTRING "${bytes}" 0 8 magic)
    if(NOT magic STREQUAL "03022307")
        message(FATAL_ERROR "Expected little-endian SPIR-V magic: ${${stage}}")
    endif()
    math(EXPR words "${hex_length} / 8")
    string(TOLOWER "${stage}" stage_name)
    string(APPEND header "inline constexpr std::array<std::uint32_t, ${words}> frame_${stage_name}_spv{\n")
    math(EXPR last "${hex_length} - 8")
    foreach(offset RANGE 0 ${last} 8)
        string(SUBSTRING "${bytes}" ${offset} 8 word)
        string(REGEX REPLACE "^(..)(..)(..)(..)$" "0x\\4\\3\\2\\1u," word "${word}")
        string(APPEND header "    ${word}\n")
    endforeach()
    string(APPEND header "};\n")
endforeach()
string(APPEND header "}\n")
file(WRITE "${OUTPUT}" "${header}")
